let ds= document.querySelector(".danh_sach")
let listButton = document.querySelector(".listbutton")
let previous = document.querySelector(".previous")
let next = document.querySelector(".next")

let json = [
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "49,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "27,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "20,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "30,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "29,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "50,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "35,000 VND"},
    {"image":"anh.jpg","name":"Unknow","author":"unknow","price": "37,000 VND"},

]
let soluong = 15
let total = json.length
let page = 1

function show(i) {
    listButton.innerHTML = i;
    let classRemove = ds.querySelector(".classitem");
    if (classRemove != null) {
        ds.removeChild(classRemove);
    }

    let start = (i - 1) * soluong;
    let end = Math.min(i * soluong, json.length);

    let classitem = document.createElement("div");
    classitem.className = "classitem grid-3x5";

    for (let idx = start; idx < end; idx++) {
        let element = json[idx];
        if (element != null) {
            let div = document.createElement("div");
            div.className = "item";

            let img = document.createElement("img");
            img.src = element.image;
            img.alt = element.name;

            let ul = document.createElement("ul");
            ul.className = "list listtest";
            let li2 = document.createElement("li");
            li2.textContent = "Tên sách: " + element.name;
            let li3 = document.createElement("li");
            li3.textContent = "Tác giả: " + element.author;
            let li4 = document.createElement("li");
            li4.textContent = "Giá: " + element.price;

            ul.append(li2, li3, li4);

            div.appendChild(img);
            div.appendChild(ul);

            classitem.appendChild(div);
        }
    }

    ds.appendChild(classitem);
}

previous.addEventListener("click", () => {
    if (page > 1) {
        page--;
        show(page);
    }
});
next.addEventListener("click", () => {
    if (page < Math.ceil(total / soluong)) {
        page++;
        show(page);
    }
});

show(page);